In [32]:
import torch

### Pytorch tensors

In [37]:
x = torch.rand(5,3,2,5,dtype=torch.float32)

In [38]:
print(x)

tensor([[[[0.1460, 0.8825, 0.6438, 0.4336, 0.1911],
          [0.9812, 0.5310, 0.0838, 0.2805, 0.2692]],

         [[0.0802, 0.2300, 0.9589, 0.2150, 0.0416],
          [0.6464, 0.6518, 0.9000, 0.6495, 0.4209]],

         [[0.6109, 0.2657, 0.5288, 0.1069, 0.5197],
          [0.2258, 0.8225, 0.7884, 0.9494, 0.6119]]],


        [[[0.5528, 0.0561, 0.9091, 0.6739, 0.6280],
          [0.6519, 0.5211, 0.7641, 0.1716, 0.0120]],

         [[0.4496, 0.3928, 0.5784, 0.5843, 0.9224],
          [0.7946, 0.1475, 0.8063, 0.1743, 0.8667]],

         [[0.6172, 0.7934, 0.1816, 0.3671, 0.2775],
          [0.0714, 0.4820, 0.0803, 0.0004, 0.4915]]],


        [[[0.4551, 0.9095, 0.8701, 0.9869, 0.3168],
          [0.7442, 0.6234, 0.5293, 0.3613, 0.1558]],

         [[0.9670, 0.9005, 0.3199, 0.3455, 0.6901],
          [0.7098, 0.6788, 0.8084, 0.9827, 0.8966]],

         [[0.4619, 0.1768, 0.6093, 0.8741, 0.8569],
          [0.8684, 0.2695, 0.9154, 0.7670, 0.1191]]],


        [[[0.8838, 0.3115, 0.5896, 0.691

In [41]:
o = torch.ones(3,4)

In [42]:
print(o)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [43]:
t = torch.rand_like(o)

In [44]:
print(t)

tensor([[0.8474, 0.6500, 0.4721, 0.1488],
        [0.5955, 0.4330, 0.2187, 0.2151],
        [0.2483, 0.4802, 0.1188, 0.4157]])


In [45]:
t.size(), o.size(), x.size()

(torch.Size([3, 4]), torch.Size([3, 4]), torch.Size([5, 3, 2, 5]))

### AutoGrad And Functions

In [29]:
x = torch.rand(2,3,requires_grad=True)

In [30]:
y = x + 2

In [31]:
print(x,"\n",y)

tensor([[0.9969, 0.2313, 0.1235],
        [0.8174, 0.3584, 0.0620]], requires_grad=True) 
 tensor([[2.9969, 2.2313, 2.1235],
        [2.8174, 2.3584, 2.0620]], grad_fn=<AddBackward>)


In [12]:
z = y * y * 3

In [13]:
out = z.mean()

In [14]:
print(z, out)

tensor([[23.7908, 22.7481, 19.1191],
        [12.0523, 12.4505, 20.1659]], grad_fn=<MulBackward>) tensor(18.3878, grad_fn=<MeanBackward1>)


In [15]:
out.backward(retain_graph=True)

In [16]:
x.grad

tensor([[2.8161, 2.7537, 2.5245],
        [2.0044, 2.0372, 2.5927]])

In [17]:
z.backward(torch.rand_like(z), retain_graph=True)

In [18]:
x.grad

tensor([[7.8184, 7.9055, 5.5360],
        [5.4508, 3.7848, 2.6698]])